# DO NOT RUN DIRECTLY

#!/bin/bash
#SBATCH –job-name=EXAMPLE-NAME_changed-OMP_NUM_THREADS
#SBATCH --output=EXAMPLE-NAME_changed-OMP_NUM_THREADS.txt
#SBATCH --ntasks=OMP_NUM_THREADS

OMP_NUM_THREADS=OMP_NUM_THREADS ./EXENAME